version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
      - TZ=America/La_Paz  # Set time zone to Bolivia
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
